---
- name: Validate the selected Filebeat container engine
  ansible.builtin.assert:
    that:
      - logging_filebeat_oci_engine in ['docker', 'podman']
    fail_msg: >-
      logging_filebeat_oci_engine must be either 'docker' or 'podman'.

- name: Prepare Filebeat configuration
  ansible.builtin.include_tasks: install-filebeat-common.yml

- name: Install Filebeat with Docker
  when: logging_filebeat_oci_engine == 'docker'
  ansible.builtin.include_tasks: install-filebeat-docker.yml

- name: Install Filebeat with Podman
  when: logging_filebeat_oci_engine == 'podman'
  ansible.builtin.include_tasks: install-filebeat-podman.yml
