"""Displaying the tables: Markdown and CSV output.

Takes the rows built by :mod:`describe` and writes them out. This module holds
every formatting decision — column mark-up, the surrounding prose, the CSV file
names — and nothing about what the rules mean.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

from describe import (
    AGGREGATION_HEADERS,
    DERIVED_HEADERS,
    THRESHOLD_HEADERS,
    aggregation_rows,
    derived_rows,
    threshold_rows,
)
from rules import RULES_DIR, RuleSet


def _markdown_table(
    headers: list[str],
    rows: list[list[str]],
    name_columns: set[int] = frozenset(),
    code_columns: set[int] = frozenset(),
    names: set[str] = frozenset(),
) -> str:
    """name_columns hold comma-separated identifiers, code_columns whole
    expressions; identifiers in any other column are marked up via `names`."""
    pattern = (
        re.compile(r"(?<![`\w:])(" + "|".join(sorted(map(re.escape, names), key=len, reverse=True)) + r")(?![\w:])")
        if names
        else None
    )

    def cell(index: int, value: str) -> str:
        value = " ".join(value.split())
        if not value:
            return ""
        if index in name_columns and value != "none":
            return ", ".join(f"`{part}`" for part in value.split(", "))
        if index in code_columns:
            return f"`{value}`".replace("|", "\\|")
        value = value.replace("|", "\\|")
        return pattern.sub(r"`\1`", value) if pattern else value

    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for row in rows:
        lines.append("| " + " | ".join(cell(i, value) for i, value in enumerate(row)) + " |")
    return "\n".join(lines)


def _intervals(ruleset: RuleSet, kind: str) -> set[str]:
    return {rule.interval for rule in ruleset.rules if rule.kind == kind and rule.interval}


def render_markdown(
    ruleset: RuleSet, args, problems: list[str], origin: str, script: str
) -> str:
    thresholds = threshold_rows(ruleset, problems)
    aggregations = aggregation_rows(ruleset, problems)
    names = set(ruleset.by_record)

    parts = [
        "# FHS Prometheus rules",
        "",
        f"Generated by `{script}` from "
        f"`{RULES_DIR}/threshold_rules.yml` and `{RULES_DIR}/aggregation_rules.yml` "
        f"at {origin}. Do not edit by hand.",
        "",
        "Every rule records `1` when it trips and `0` otherwise, so a rule that is "
        "`1` is the thing that failed.",
        "",
        "## Threshold rules",
        "",
        f"{len(thresholds)} checks against scraped metrics."
        + _interval_note(_intervals(ruleset, "threshold")),
        "",
        _markdown_table(THRESHOLD_HEADERS, thresholds, {0, 3}, names=names),
        "",
        "## Aggregation rules",
        "",
        f"{len(aggregations)} component health states, each built from the threshold "
        "rules listed as its child metrics."
        + _interval_note(_intervals(ruleset, "aggregation")),
        "",
        _markdown_table(AGGREGATION_HEADERS, aggregations, {0, 1}, names=names),
    ]

    if not args.no_derived:
        derived = derived_rows(ruleset)
        parts += [
            "",
            "## Derived metrics",
            "",
            f"{len(derived)} intermediate calculations. They are not checks; the "
            "threshold rules above compare against them.",
            "",
            _markdown_table(DERIVED_HEADERS, derived, {0, 1}, code_columns={2}),
        ]

    if problems:
        parts += [
            "",
            "## Not described",
            "",
            "These expressions did not match a known shape and need a look by hand:",
            "",
            *[f"- `{problem}`" for problem in problems],
        ]
    return "\n".join(parts) + "\n"


def _interval_note(intervals: set[str]) -> str:
    if len(intervals) == 1:
        return f" All of them re-evaluate every {intervals.pop()}."
    return ""


def write_csv(directory: Path, ruleset: RuleSet, problems: list[str], include_derived: bool) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    tables = {
        "threshold_rules.csv": (THRESHOLD_HEADERS, threshold_rows(ruleset, problems)),
        "aggregation_rules.csv": (AGGREGATION_HEADERS, aggregation_rows(ruleset, problems)),
    }
    if include_derived:
        tables["derived_metrics.csv"] = (DERIVED_HEADERS, derived_rows(ruleset))
    for name, (headers, rows) in tables.items():
        with (directory / name).open("w", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(headers)
            writer.writerows(rows)
